# Link with locally built libraries
set(FLAC_LIBRARY $ENV{FLAC_LIBS})
set(FLAC_INCLUDE_DIR $ENV{FLAC_INCLUDE})

set(OGG_LIBRARY $ENV{OGG_LIBS})
set(OGG_INCLUDE_DIR $ENV{OGG_INCLUDE})

set(Vorbis_Vorbis_LIBRARY $ENV{VORBIS_LIBS})
set(Vorbis_Vorbis_INCLUDE_DIR $ENV{VORBIS_INCLUDE})

set(Vorbis_Enc_LIBRARY $ENV{VORBISENC_LIBS})
set(Vorbis_Enc_INCLUDE_DIR $ENV{VORBISENC_INCLUDE})

set(OPUS_LIBRARY $ENV{OPUS_LIBS})
set(OPUS_INCLUDE_DIR $ENV{OPUS_INCLUDE})

set(MP3LAME_LIBRARY $ENV{MP3LAME_LIBS})
set(MP3LAME_INCLUDE_DIR $ENV{MP3LAME_INCLUDE})

set(mpg123_LIBRARY $ENV{MPG123_LIBS})
set(mpg123_INCLUDE_DIR $ENV{MPG123_INCLUDE})
